### ISSUE TITLE
add a tl;dr to the top

### ISSUE THREAD

**Issue by chendaniely** [public-health-data-scientists/open-coding-labs#1]
mostly for people who've been here before,

we can add a section for 'if you are new here keep reading' people (which is the current readme state)

**Comment by cosmicBboy** [comment]
like, a link that goes straight to the wiki at the top?

**Comment by chendaniely** [comment]
yeah something like that

**Comment by chendaniely** [comment]
fixed in c5427b72413a6c070a4c3d4b2533ba97a3ddddbd
